name: 'MTT-Net' # ⚠️ 默认: 'MTT-Net'，若不是，请改正

# ====== 重要参数 ======
use_seed: false
seed: 42 # 随机种子

phase: 'train' # 训练阶段
isTrain: true # GAN_class.py需要（待优化）

need_bugfree: true # ⚠️ 整活用私货，不需要请禁用

use_Liu_dataset: true # 是否使用Liu数据集 # ⚠️默认: false，若不是，请改正
# ===== DATASET ===== 
preload: true # 直接放入内存

# 目前未实现不加载训练集的方法（test可无, train不可无）
#（传入不划分的测试集到train_set也可以用evaluate()进行评估）
need_validation: true # 是否将训练集划分为训练集和验证集
validation_ratio: 0.2 # 验证集比例
train_root: [
  # '/home/featurize/data/Task1/brain',
  # '/home/featurize/data/Task1/pelvis',
  '/home/featurize/data/Task1_N4BFC/brain',
  # '/home/featurize/data/Task1_N4BFC/pelvis', # 尚未配准完
]
train_label: [
  # 0,
  # 1,
  0,
  # 1, # 尚未配准完
]

need_test: false # 是否进行测试 # 不然不用加载test_root
test_root: [ # [not implemented]
  '/home/featurize/data/Task1/brain', 
]
test_label: [
  0
]


# 忽略文件ID
ignore_ids: [
  'overview',
]

start_slice: 61 # 切片开始的位置（默认从数据中间取,start_slice不为-1时,从start_slice开始取）
target_depth_size: 32 # 数据切留的厚度
# target_depth_size: 64 # Liu给的数据 (batch_size:1 时，显存为 23 768 MB)
target_image_size: 256 # 切片数据的H,W

# ct窗位
ct_window_level: 32
ct_window_width: 80

data_tange: 2.0 # 目标输出，值域[-1~1]

# ===== TRAINER ===== 
gpu_ids: [0]
num_workers: 4 # 线程数
batch_size: 1 # 批量大小（量力而行。batch_size为1时，nvidia-smi显示中占用显存 13 068 MB）

use_reg: true # 加入RegGAN的RegNet
isTrain: true # 是否训练

start_epoch: 0 # 从第几轮开始训练 # 当不是0时，会尝试读取上次训练的模型
num_epochs: 201 # 训练总轮数
eval_interval: 5 # 每eval_interval代评估一次

# 模型参数（不用看）
input_nc: 1 # 输入通道数
output_nc: 1 # 输出通道数
G_model: 'MTTNET' # 生成器模型
D_model: 'wave3DDiscriminator' # 判别器模型
R_model: 'Reg' # Reg模型
ngf: 16
ndf: 16
n_layers_D: 2 # only used if netD==n_layers
G_norm: 'instance' # 生成器归一化方式
D_norm: 'instance' # 判别器归一化方式
init_type: 'normal' # 权重初始化方式
init_gain: 0.02 # 权重初始化增益
no_dropout: false # 是否使用dropout
load_name: 'latest'



# 超参数
lambda_L1: 20
Adv_lambda: 1
SR_lambda: 20
SM_lambda: 10 # smooth lambda
VGG_loss: true # 是否使用VGG loss
pretrain_model_path: 'perceive_loss/vgg19-dcbb9e9d.pth'
beta1: 0.5 # Adam优化器参数
beta2: 0.999 # Adam优化器参数
lr_max: 0.0002 # 学习率
gan_mode: 'vanilla' # GAN模式 [vanilla| lsgan ｜ wgangp] 如：vanilla: cross-entropy objective

# 日志等需要的
output_root: '/home/featurize/data/output' # 实际位置在 {log_dir}/{name}

# 保留的原始参数（待优化）
Npatch: 24
print_freq_num: 4
disx: 10120 # 10120, 100000
continue_train: false # 是否继续训练(由start_epoch决定)


# ===== 整活 =====
bugfree:
  bugfree_img_path: '/home/featurize/work/CT2MRI-MTTNet/util/bugfree_img/' # bugfree图片路径
  img_name: buddha.bugfree # bugfree图片名称 # buddha.buggfree
  start_color: FF7EC7 # bugfree图片起始颜色
  end_color: FFED46 # bugfree图片结束颜色



# ==== 另外的数据集 ====
# ⚠️启用Liu的数据时使用，没有的话可以注释掉
Liu_dataset:
  # 训练CT数据路径
  trainCT_root: [
    # '/home/featurize/data/TRAINNING/CT',
    '/home/featurize/data/Task1_Liu_split_32/train/CT'
  ]
  # 训练MR数据路径
  trainMR_root: [
    '/home/featurize/data/Task1_Liu_split_32/train/MR',
  ]
  # 测试CT路径
  testCT_root: [
    '/home/featurize/data/Task1_Liu_split_32/val/CT',
  ]
  # 测试MR路径 
  testMR_root: [
    '/home/featurize/data/Task1_Liu_split_32/val/MR',
  ]
  preload: true  # 将dataset直接加入内存

